Lection 3 tooltip task solution
js-tasks-ru/htmlcss-20210513_mrmldsky27 pull request #12
Opened 2021-06-04 07:30 UTC by t-pyrope

2021-06-04 07:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-05 19:22 UTC, GSemikozov requested changes

2021-06-05 19:22 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
и еще надо бы задать display: inline-block | inline-flex (иначе блок будет растягиваться на всю ширину и из-за этого могут быть проблемы с позиционированием дочерних элементов)

2021-06-05 19:22 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    opacity: 0;
если скрыть только через opacity - элемент будет оставаться в DOM. и при этом все еще доступен для взаимодействия с пользователем - будет перекрывать собой другие элементы и на него можно нажать. Поэтому - в дополнение к opacity стоит еще использовать visibility: hidden | visible

2021-06-06 15:39 UTC, t-pyrope commented on 05-lection3/01-tooltip/tooltip.css
> +    opacity: 0;
Спасибо!

2021-06-06 15:39 UTC, t-pyrope commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
Спасибо!

2021-06-07 08:12 UTC, GSemikozov approved these changes

2021-06-07 08:13 UTC, merged