Added solution for modal task
js-tasks-ru/htmlcss-20210513_mrmldsky27 pull request #13
Opened 2021-06-04 11:00 UTC by t-pyrope

2021-06-04 11:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-05 19:29 UTC, GSemikozov requested changes

2021-06-05 19:29 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
position: fixed лучше закинуть сразу на сам блок - .modal, а wrapper и overlay будут позиционироваться через absolute уже относительно него

2021-06-05 19:29 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    z-index: 4000;
слишком произвольное значение) если у .modal будет position: fixed, то для overlay достаточно задать z-index:1 , а для wrapper - z-index: 2

2021-06-05 19:29 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    justify-content: space-between;
можно еще и по вертикали по середине выравнивать - align-items: center

2021-06-05 19:29 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__body {
мне кажется, в целом с внутренними отступами немного не доработано: у wrapper должен быть какой-то общий для всего внутреннего контента отступ, либо у header и body - отдельно

2021-06-06 15:47 UTC, t-pyrope commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
Спасибо!

2021-06-06 15:49 UTC, t-pyrope commented on 05-lection3/02-modal/modal.css
> +    z-index: 4000;
Спасибо!

2021-06-06 15:55 UTC, t-pyrope commented on 05-lection3/02-modal/modal.css
> +    justify-content: space-between;
Спасибо!

2021-06-06 15:58 UTC, t-pyrope commented on 05-lection3/02-modal/modal.css
> +.modal__body {
Спасибо!

2021-06-08 13:42 UTC, GSemikozov requested changes

2021-06-08 13:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
только тут position: relative; лишнее - выше уже определено через absolute ;)

2021-06-08 19:17 UTC, t-pyrope commented on 05-lection3/02-modal/modal.css
> +    position: relative;
Спасибо!

2021-06-11 08:57 UTC, GSemikozov approved these changes

2021-06-11 08:58 UTC, merged