Added solution for lection 5 toggler task
js-tasks-ru/htmlcss-20210513_mrmldsky27 pull request #17
Opened 2021-06-05 07:58 UTC by t-pyrope

2021-06-05 07:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-05 19:45 UTC, GSemikozov requested changes

2021-06-05 19:45 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    transform: translate(23px, -50%);
еще иконка должна сменить цвет на белый как в дизайне

2021-06-06 15:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-06 16:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-06 16:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-06 16:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-06 16:22 UTC, t-pyrope commented on 07-lection5/03-toggler/toggler.css
> +    transform: translate(23px, -50%);
Спасибо!

2021-06-06 16:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-06 17:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-08 13:46 UTC, GSemikozov approved these changes

2021-06-08 13:46 UTC, merged