Lection 1 buttons-task solution
js-tasks-ru/htmlcss-20210513_mrmldsky27 pull request #2
Opened 2021-05-19 08:29 UTC by t-pyrope

2021-05-19 08:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-22 20:31 UTC, GSemikozov requested changes

2021-05-22 20:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.group {
в целом по проекту мы будем использовать кнопки как отдельные и независимые компоненты, нет необходимости создавать `.group`. В данном случае это вспомогательные стили для  размещения кнопок в определенной сетке. Поэтому - все стили для сетки нужно убрать из этого файла, оставляем только то что относится к кнопке самой по себе. Соответственно, нужно будет поправить классы по БЭМ.

2021-05-22 20:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.group__button {
как я уже упомянул выше - здесь будет просто `button`, а не `group__button`.

2021-05-26 10:10 UTC, t-pyrope commented on 03-lection1/01-button/button.css
> +.group {
Ок, сделано!

2021-05-26 10:12 UTC, t-pyrope commented on 03-lection1/01-button/button.css
> +.group__button {
👍

2021-05-26 22:30 UTC, GSemikozov requested changes

2021-05-26 22:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
фиксированную ширину решили не ставить, пусть ширина определятся внутренним содержимым, а если надо растянуть по родителю - добавим модификатор `.button_full-width { width: 100% }`

2021-05-26 22:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 0rem 0.5rem 0.5rem 0rem;
внешние отступы не стоит добавлять блоку - это делается на этапе встраивания в другой блок или сетку, и тогда через родительский элемент можно будет добавить класс, который будет определять нужное поведение для нашего блока в сетке / в другом блоке (это тема про миксы, обсуждали на первом занятии, советую освежить знания по статье об именовании классов по БЭМ ;)).

2021-05-26 22:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: #4263EB;
можно этот синий поставить вместо того, который сейчас primary в переменных

2021-05-27 11:39 UTC, t-pyrope commented on 03-lection1/01-button/button.css
> +    background-color: #4263EB;
Извините, вы имеете в виду поставить его в main.css в --primary?

2021-05-27 12:15 UTC, t-pyrope commented on 03-lection1/01-button/button.css
> +    margin: 0rem 0.5rem 0.5rem 0rem;
Хорошо 👍 Извините

2021-05-27 12:16 UTC, t-pyrope commented on 03-lection1/01-button/button.css
> +    width: 189px;
А паддинги в пикселях добавить это норм?

2021-05-30 11:10 UTC, GSemikozov approved these changes

2021-05-30 11:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: #4263EB;
ага

2021-05-30 11:10 UTC, merged