Added solution for lection 1. accordion task
js-tasks-ru/htmlcss-20210513_mrmldsky27 pull request #3
Opened 2021-05-19 10:13 UTC by t-pyrope

2021-05-19 10:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-22 20:36 UTC, GSemikozov requested changes

2021-05-22 20:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.grid {
здесь та же история что. и в предыдущем ПР - весь этот "грид" нужно уносить из этого файла либо в тэг style html-файла в котором добавляется решение задачи, либо в отдельный css-файл который подключается к этому же html. А в аккордион.css должны быть стили которые касаются только аккордиона

2021-05-22 20:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    content: url("data:image/svg+xml,%3Csvg width='18' height='10' viewBox='0 0 18 10' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L9 9L17 1' stroke='%23495057' stroke-width='2' s
base64 это хорошо

2021-05-26 10:12 UTC, t-pyrope commented on 03-lection1/02-accordion/accordion.css
> +.grid {
Исправлено

2021-05-26 10:16 UTC, t-pyrope commented on 03-lection1/02-accordion/accordion.css
> +    content: url("data:image/svg+xml,%3Csvg width='18' height='10' viewBox='0 0 18 10' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L9 9L17 1' stroke='%23495057' stroke-width='2' s
Спасибо! На самом деле я скопировала этот код из фигмы и не совсем понимаю, что такое base64, пока что не совсем понятно из описаний в википедии и на developer.mozilla.org, но запомню на будущее!

2021-05-26 22:31 UTC, GSemikozov approved these changes

2021-05-26 22:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    content: url("data:image/svg+xml,%3Csvg width='18' height='10' viewBox='0 0 18 10' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L9 9L17 1' stroke='%23495057' stroke-width='2' s
возможно, когда будем обсуждать адаптивные картинки, я покажу что это такое)

2021-05-26 22:31 UTC, merged